I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 52, in script call
    call prologue # done
  File "renpy/common/00start.rpy", line 81, in script
    return
  File "game/script.rpy", line 52, in script call
    call prologue # done
  File "renpy/common/00start.rpy", line 81, in script
    return
ScriptError: could not find label '(u'C:\\Users\\owner\\Documents\\GitHub\\Kirei-Git\\Kirei/game/script_prologue.rpy', 1404719590, 0)'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\owner\Documents\GitHub\Kirei-Git\renpy\bootstrap.py", line 285, in bootstrap
    renpy.main.main()
  File "C:\Users\owner\Documents\GitHub\Kirei-Git\renpy\main.py", line 349, in main
    run(restart)
  File "C:\Users\owner\Documents\GitHub\Kirei-Git\renpy\main.py", line 77, in run
    renpy.execution.run_context(True)
  File "C:\Users\owner\Documents\GitHub\Kirei-Git\renpy\execution.py", line 515, in run_context
    context.run()
  File "game/script.rpy", line 52, in script call
    call prologue # done
  File "renpy/common/00start.rpy", line 81, in script
    return
  File "C:\Users\owner\Documents\GitHub\Kirei-Git\renpy\ast.py", line 1286, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "game/script.rpy", line 52, in script call
    call prologue # done
  File "renpy/common/00start.rpy", line 81, in script
    return
  File "C:\Users\owner\Documents\GitHub\Kirei-Git\renpy\script.py", line 549, in lookup
    raise ScriptError("could not find label '%s'." % str(label))
ScriptError: could not find label '(u'C:\\Users\\owner\\Documents\\GitHub\\Kirei-Git\\Kirei/game/script_prologue.rpy', 1404719590, 0)'.

Windows-7-6.1.7601-SP1
Ren'Py 6.17.6.512
Pretty 1.0
